"""Find public AI-generated repos on GitHub (unauthenticated repo search).

Buckets of heuristics, each a repo-search query. Rate limit: 10 searches/min
unauthenticated, so we sleep between calls. Output: repos.json (resumable
state shared with run_all.py).
"""

import json
import time

import requests

from config import REPOS_STATE

API = "https://api.github.com/search/repositories"
HEADERS = {"User-Agent": "vibe-code-study", "Accept": "application/vnd.github+json"}

# Common quality filters: no forks, recent activity, sane size (KB).
COMMON = "fork:false size:150..100000 pushed:>2026-01-01"

BUCKETS = [
    # (origin, query, pages of 100)
    ("lovable", f'"Welcome to your Lovable project" in:readme {COMMON}', 2),
    ("v0", f'"Automatically synced with your v0.app deployments" in:readme {COMMON}', 1),
    ("v0", f'"Generated by v0" in:readme {COMMON}', 1),
    ("bolt", f'"bolt.new" in:readme {COMMON}', 1),
    ("generic-ai", f"topic:ai-generated {COMMON}", 1),
    ("generic-ai", f"topic:vibe-coding {COMMON}", 1),
]

MAX_PER_OWNER = 2
LANGUAGES = {"TypeScript", "JavaScript", "Python", "PHP", "HTML", "Vue", "Svelte"}


def _search(query, page):
    params = {"q": query, "per_page": 100, "page": page, "sort": "updated", "order": "desc"}
    resp = requests.get(API, params=params, headers=HEADERS, timeout=30)
    if resp.status_code == 403:
        print("  rate limited, sleeping 65s...")
        time.sleep(65)
        resp = requests.get(API, params=params, headers=HEADERS, timeout=30)
    resp.raise_for_status()
    return resp.json().get("items", [])


def _to_candidate(item, origin):
    return {
        "slug": item["full_name"].replace("/", "__"),
        "full_name": item["full_name"],
        "clone_url": item["clone_url"],
        "origin": origin,
        "language": item.get("language"),
        "size_kb": item.get("size"),
        "stars": item.get("stargazers_count", 0),
        "pushed_at": item.get("pushed_at"),
        "created_at": item.get("created_at"),
        "status": "candidate",
    }


def discover():
    existing = {}
    if REPOS_STATE.exists():
        existing = {r["full_name"]: r for r in json.loads(REPOS_STATE.read_text(encoding="utf-8"))}

    owners = {}
    for repo in existing.values():
        owners[repo["full_name"].split("/")[0]] = owners.get(repo["full_name"].split("/")[0], 0) + 1

    added = 0
    for origin, query, pages in BUCKETS:
        for page in range(1, pages + 1):
            print(f"[discover] {origin} page {page}: {query[:70]}...")
            items = _search(query, page)
            for item in items:
                owner = item["full_name"].split("/")[0]
                if item["full_name"] in existing:
                    continue
                if item.get("language") not in LANGUAGES:
                    continue
                if owners.get(owner, 0) >= MAX_PER_OWNER:
                    continue
                owners[owner] = owners.get(owner, 0) + 1
                existing[item["full_name"]] = _to_candidate(item, origin)
                added += 1
            time.sleep(7)  # stay under 10 searches/min

    repos = sorted(existing.values(), key=lambda r: (r["origin"], r["full_name"]))
    REPOS_STATE.write_text(json.dumps(repos, indent=1), encoding="utf-8")

    by_origin = {}
    for r in repos:
        by_origin[r["origin"]] = by_origin.get(r["origin"], 0) + 1
    print(f"\n[discover] total candidates: {len(repos)} (+{added} new) by origin: {by_origin}")


if __name__ == "__main__":
    discover()
